### ISSUE TITLE
factory_bot_rails 6.0 checklist

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot_rails#349]
- [x] Stop testing against Rails 4.2
- [x] Stop testing against EOL Ruby versions
- [x] start using bundler 2 on Travis (see https://github.com/thoughtbot/factory_bot_rails/commit/ab8ed304244610529909dab137b9e9d971171633)
- [x] Get rid of Rails 4.2 branch in the railties_spec
- [x] Revisit https://github.com/thoughtbot/factory_bot_rails/pull/343
- [x] Release factory_bot 6
- [ ] Bump runtime dependencies in the gemspec

**Comment by composerinteralia** [comment]
Started some of this in https://github.com/thoughtbot/factory_bot_rails/pull/367

**Comment by composerinteralia** [comment]
Updated the Travis ruby versions in https://github.com/thoughtbot/factory_bot_rails/pull/374. Ruby 2.4 may be EOL by the time we release this, so we may want to drop support for that as well.

Let's check https://www.ruby-lang.org/en/downloads/branches/ before the final release.
