### ISSUE TITLE
The railtie included in #419 breaks compatibility with some gems "undefined method `config' for nil:NilClass" Factory Bot > 6.2.0

### ISSUE THREAD

**Issue by tagliala** [thoughtbot/factory_bot_rails#426]
Hello,

I was testing the main branch and the application didn't boot because of this error:

```
~/.rvm/gems/ruby-3.2.2/gems/railties-7.0.8/lib/rails.rb:47:in `configuration': undefined method `config' for nil:NilClass (NoMethodError)

      application.config
                 ^^^^^^^
	from ~/.rvm/gems/ruby-3.2.2/bundler/gems/factory_bot_rails-b965bb8f6430/lib/factory_bot_rails/railtie.rb:25:in `block in <class:Railtie>'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:75:in `each'
	from ~/.rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
	from ~/.rvm/gems/ruby-3.2.2/gems/activerecord-7.0.8/lib/active_record/base.rb:333:in `<module:ActiveRecord>'
	from ~/.rvm/gems/ruby-3.2.2/gems/activerecord-7.0.8/lib/active_record/base.rb:15:in `<main>'
```

**I think that this is not an issue with Factory Bot Rails**, but it is a problem with third-party gems or implementations that does not rely on lazy hooks or autoload to add new modules to `ActiveRecord::Base.`

I opened this here because updating factory bot triggers this behavior and may affect other users that may search here for a solution

### Reproduction Steps

1. Add [database_cleaner-active_record](https://github.com/DatabaseCleaner/database_cleaner-active_record) to `Gemfile` (or call `ActiveRecord::Base` before the module block of  `config/application.rb`)
2. run `rails c`

### Expected behavior

Console opens

### Actual behavior

Console does not open and raises an error

### System configuration
**factory_bot_rails version**:  main 
**factory_bot version**:  6.3.0
**rails version**:  7.0.8
**ruby version**: 3.2.2/3.0.4

Bisected to: b965bb8

### Affected gems
- [x] [amoeba](https://github.com/amoeba-rb/amoeba) amoeba-rb/amoeba#115
- [ ] [database_cleaner-active_record](https://github.com/DatabaseCleaner/database_cleaner-active_record) DatabaseCleaner/database_cleaner-active_record#89
- [x] [chronomodel](https://github.com/ifad/chronomodel) ifad/chronomodel#232

**Comment by tagliala** [comment]
Reopen because of https://github.com/thoughtbot/factory_bot_rails/issues/426

**Comment by tagliala** [comment]
Closing again in favour of #433

**Comment by marclennox** [comment]
Thanks @tagliala , this merge request fixes the issue.  Until this gets merged, I'll just use a forked copy of factorybot_rails with this change applied.
